---
title: "Covid-19 trials"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
source(here::here("covid_class.R"), encoding = "UTF-8")
options(DT.options = list(scrollY="100vh"))
```

Column {.sidebar}
-------------------------------------
### Última atualização
```{r}
valueBox(format(as.POSIXct(Sys.time()),format='%Y-%m-%d %H:%M'))
```

<!-- ------------------------------------- -->
<!-- ### Trials na base americana -->
<!-- ```{r} -->
<!-- valueBox(nrow(eua)) -->
<!-- ``` -->

-------------------------------------
### Total de trials na base da OMS
```{r}
valueBox(nrow(dados_oms_tudo))  
```
  
Link para dados completos: <https://www.who.int/ictrp/COVID19-web.csv>

-------------------------------------
### Trials intervencionais na base da OMS
```{r}
valueBox(nrow(dados_oms))
```
<!-- ### Trials na base da China -->
<!-- ```{r} -->
<!-- valueBox(nrow(china)) -->
<!-- ``` -->

<!-- Extraidos da base da OMS + busca por outros mais recentes  -->

<!-- ### Protocolos na base da União Europeia -->
<!-- ```{r} -->
<!-- valueBox(nrow(eu_data)) -->
<!-- ``` -->

<!-- Um trial pode ter protocolos diferentes em cada país participante -->


Column {.tabset .tabset-fade}
-------------------------------------
### Grupos
```{r}
DT::datatable(tab_grupos,
              options = list(dom = 'tpi'),
              caption = "Grupos")
```

### Categorias
```{r}
DT::datatable(tab_categorias,
              options = list(dom = 'tpi'),
              caption = "Categorias")
```

### Substâncias
```{r}
DT::datatable(tab_substancias,
              options = list(dom = 'tpi'),
              caption = 'Substâncias (apenas trials do grupo "Drogas")')
```

### Países
```{r}
DT::datatable(tab_paises,
              options = list(dom = 'tpi'))
```

### Dados 

```{r}
DT::datatable(dados_exibicao,
              caption = "Variáveis selecionadas; apenas trials intervencionais",
              extensions = 'Buttons',
              options = list(
                    dom = 'Bfrtip',
                    buttons = c('csv', 'excel')))
```

### Critérios de classificação 

```{r}
DT::datatable(lista_regex,
              options = list(dom = 'tip'),
              caption = '**regex** = regular expression (padrões textuais); **variavel** = onde o padrão é buscado: Intervention ou Scientific title+Intervention ("concat")')
```




<!-- ### Drogas EUA  -->

<!-- ```{r} -->
<!-- DT::datatable(drugs_grupos_count,   -->
<!--               extensions = 'Buttons', -->
<!--               options = list( -->
<!--                     dom = 'Bfrtip', -->
<!--                     buttons = c('csv', 'excel')) -->
<!--               ) -->
<!-- ```    -->

<!-- ### Nomes de substâncias UE -->

<!-- ```{r} -->
<!-- DT::datatable(eu_substance_count,   -->
<!--               extensions = 'Buttons', -->
<!--               options = list( -->
<!--                     dom = 'Bfrtip', -->
<!--                     buttons = c('csv', 'excel')) -->
<!--               ) -->
<!-- ``` -->


<!-- ### Dados EUA -->

<!-- ```{r} -->
<!-- DT::datatable(eua, filter = "top",   -->
<!--               extensions = 'Buttons', -->
<!--               options = list( -->
<!--                     dom = 'Bfrtip', -->
<!--                     buttons = c('csv', 'excel')) -->
<!--               ) -->
<!-- ```    -->

<!-- ### Dados China -->
<!-- ```{r} -->
<!-- DT::datatable(china, filter = "top", -->
<!--               extensions = 'Buttons', -->
<!--               options = list( -->
<!--                     dom = 'Bfrtip', -->
<!--                     buttons = c('csv', 'excel')) -->
<!--               ) -->
<!-- ``` -->

<!-- ### Dados UE -->
<!-- ```{r} -->
<!-- DT::datatable(eu_data, filter = "top",   -->
<!--               extensions = 'Buttons', -->
<!--               options = list( -->
<!--                     dom = 'Bfrtip', -->
<!--                     buttons = c('csv', 'excel')) -->
<!--               ) -->
<!-- ```    -->


<!-- ### Dados OMS -->

<!-- ```{r} -->
<!-- DT::datatable(select(oms, -`Inclusion Criteria`, -`Exclusion Criteria`),  -->
<!--               filter = "top",   -->
<!--               extensions = 'Buttons', -->
<!--               options = list( -->
<!--                     dom = 'Bfrtip', -->
<!--                     buttons = c('csv', 'excel')) -->
<!--               ) -->
<!-- ``` -->

